apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
     - containerPort: 30007
       hostPort: 30007
     - containerPort: 30008
       hostPort: 30008
  - role: worker
  - role: worker

